import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Chip } from '../components/Chip';
import { BetterAnswerCard } from '../components/BetterAnswerCard';
import { PressureQuestionCard } from '../components/PressureQuestionCard';
import { RecordButtonMock } from '../components/RecordButtonMock';
import { SafePhraseChip } from '../components/SafePhraseChip';
import { scenarios } from '../data/scenarios';
import { safePhrases } from '../data/phrases';
import { colors, radii, spacing, type } from '../theme';
export function DrillScreen() { const scenario = scenarios[0]; const [answer,setAnswer]=useState(''); return <View><Text style={styles.header}>PRESSURE DRILL</Text><View style={styles.row}><Chip label={scenario.category}/><Chip label={scenario.difficulty} tone='safe'/><Chip label={scenario.risk} tone='warn'/></View><Text style={styles.title}>{scenario.title}</Text><View style={styles.block}><Text style={styles.label}>SITUATION</Text><Text style={styles.copy}>{scenario.summary}</Text></View><PressureQuestionCard question={scenario.pressureQuestion} /><TextInput value={answer} onChangeText={setAnswer} style={styles.input} multiline placeholder='Type your answer with calm, clear details.' placeholderTextColor={colors.textMuted} textAlignVertical='top'/><RecordButtonMock /><Text style={styles.label}>SAFE PHRASES</Text><View style={styles.row}>{safePhrases.slice(0,3).map((p)=><SafePhraseChip key={p} label={p} />)}</View><BetterAnswerCard answer={scenario.betterAnswer} /><View style={styles.block}><Text style={styles.label}>SELF-CHECK</Text><Text style={styles.copy}>• Did I answer directly?{`\n`}• Did I keep a neutral tone?{`\n`}• Did I avoid filler and over-explaining?</Text></View><Pressable style={styles.save}><Text style={styles.saveText}>Save Practice</Text></Pressable><Text style={styles.foot}>Stored on this device. No upload.</Text></View>; }
const styles=StyleSheet.create({header:{...type.caption,color:colors.textSecondary},row:{flexDirection:'row',flexWrap:'wrap',marginTop:spacing.sm},title:{...type.h1,marginTop:spacing.sm},block:{backgroundColor:colors.card,borderRadius:radii.lg,padding:spacing.lg,borderWidth:1,borderColor:colors.borderSubtle,marginTop:spacing.md},label:{...type.caption,color:colors.textSecondary},copy:{...type.bodySmall,color:colors.textSecondary,marginTop:spacing.xs},input:{...type.body,backgroundColor:colors.surface,borderRadius:radii.lg,padding:spacing.lg,borderWidth:1,borderColor:colors.border,minHeight:130,color:colors.textPrimary,marginTop:spacing.md},save:{marginTop:spacing.lg,backgroundColor:colors.elevatedCard,borderRadius:radii.md,padding:spacing.lg,alignItems:'center',borderWidth:1,borderColor:colors.border},saveText:{...type.body,color:colors.textPrimary,fontWeight:'600'},foot:{...type.caption,color:colors.textMuted,marginTop:spacing.sm}});
