import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { PhraseCard } from '../components/PhraseCard';
import { ToneShiftCard } from '../components/ToneShiftCard';
import { avoidPhrases, safePhrases, toneShifts } from '../data/phrases';
import { colors, radii, spacing, type } from '../theme';
type Segment='safe'|'avoid'|'tone';
export function PhrasesScreen(){const [segment,setSegment]=useState<Segment>('safe');return <View><Text style={styles.header}>PHRASE BANK</Text><Text style={styles.title}>Phrases you can keep ready.</Text><View style={styles.row}>{(['safe','avoid','tone'] as Segment[]).map((s)=><Pressable key={s} onPress={()=>setSegment(s)} style={[styles.seg,segment===s&&styles.active]}><Text style={[styles.segText,segment===s&&styles.activeText]}>{s.toUpperCase()}</Text></Pressable>)}</View>{segment==='safe'&&safePhrases.slice(0,4).map((item)=><PhraseCard key={item} title='SAFE' body={item} detail='Direct phrasing that stays respectful under pressure.' tone='safe'/>)}{segment==='avoid'&&avoidPhrases.slice(0,3).map((item)=><PhraseCard key={item} title="DON'T SAY" body={item} detail='TRY INSTEAD: I want to answer clearly and accurately.' tone='danger'/>)}{segment==='tone'&&toneShifts.map((t)=><ToneShiftCard key={t.from} from={t.from} to={t.to} />)}</View>}
const styles=StyleSheet.create({header:{...type.caption,color:colors.textSecondary},title:{...type.h2,marginTop:spacing.sm},row:{flexDirection:'row',marginVertical:spacing.md,gap:spacing.sm},seg:{backgroundColor:colors.card,paddingVertical:spacing.sm,paddingHorizontal:spacing.md,borderRadius:radii.pill,borderWidth:1,borderColor:colors.borderSubtle},active:{backgroundColor:colors.elevatedCard,borderColor:colors.border},segText:{...type.caption,color:colors.textMuted},activeText:{color:colors.textPrimary}})
